### ISSUE TITLE
Timeout when Jellyfin server is behind a CDN

### ISSUE THREAD

**Issue by enigma0Z** [fredrikburmester/streamyfin#223]
**Describe the bug**
Cannot see my library on my Cloudflare fronted Jellyfin server with Streamyfin. Vanilla iOS client and web view work fine. 

**To Reproduce**
1. Put Jellyfin on a server with nginx reverse proxy in front 
2. Point cloudflare at Jellyfin server
3. Point Streamyfin at Cloudflare hostname
4. Cannot connect

**Detail**
Authentication seems to work. However nothing from the library loads, it’s all blank like it can’t even read the library metadata. No search results either when searching in library.

Local IP works too so it’s gotta be something with how Streamyfin is interacting with the CDN and reverse proxy.  

I recently updated my reverse proxy (nginx) to use the SSL hostname header to forward the requests into Jellyfin; iOS client and web view seem to be fine with this, for what it’s worth. 

The error itself feels like some kind of time out; I’d be happy to provide detailed logs if there is some way of extracting them out of the app. 

**Screenshots**
https://imgur.com/a/lgdP5dQ

**Smartphone (please complete the following information):**
 - Device: iPhone15ProMax
 - OS: iOS18
 - Version 0.18.0

**Comment by retardgerman** [comment]
Hey, sorry for getting back to you so late. We have fixed a ton of things in our [latest Release](https://github.com/fredrikburmester/streamyfin/releases/tag/v0.21.0)! Maybe try updating the app and check if it will work?  Otherwise, please get back to us!

**Comment by enigma0Z** [comment]
Oh, Sorry I forgot that this I opened this; I hope I didn't cause any wasted effort on your part, I ended up figuring out-ish what was going on, I was in the process of setting up my CDN and I think that Streamyfin cached some things that caused API calls behind the scenes to have strange behaviors.  

Funny enough, uninstalling and reinstalling didn't really fix it, so it may be even response values cached at an OS level or something (not 100% sure, I never went source diving).

Anyway, I don't have a great interest in trying to recreate this as it was _very_ broken when I posted this.  I'll leave the bug open but if you don't want to take it anywhere, I won't be upset if it gets closed.
